config/routes.rb
Rails.application.routes.draw do

	root action: :home, controller: "page"
	get 'privacy', to: 'page#privacy'
	get 'about', to: 'page#about'
	get 'home', to: 'page#home'
	get 'cookie', to: 'page#cookie'

	resources :dashboard, only: [:index] do
		collection do
			get :check
		end
	end

	resources :engines do
		resources :service_records do
			member do
				delete :remove_engine_service_record_image, to: 'service_records#remove_image', as: :remove_image
			end
		end
		member do
			delete :remove_image
		end
	end

	resources :events do
		collection do
			get :check
		end
	end

	namespace :api do
    namespace :v1 do
      resources :events, only: [:index, :show]
    end
  end

	resources :tracks do
		collection do
			get :search
		end
	end

	devise_for :users
	resources :contacts, only: [:new, :create]
	resources :championships
	resource :calendars, only: [:show]
	resources :follows, only: [:create, :destroy]

	get '*unmatched_route', to: 'application#not_found', constraints: lambda { |req|
		req.path.exclude? 'rails/active_storage'
	}

	if Rails.env.development? || Rails.env.test?
		mount Railsui::Engine, at: "/railsui"
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @display_month = params[:month] ? Date.parse(params[:month]) : Date.today
    @timeline_events = Event.where(championship: @followed_championships)
                        .or(Event.followed_by(current_user))
                        .order('start_date ASC')
                        .where("start_date >= ?", Date.today)
                        .limit(15)
    @engines = current_user.engines
    @service_records = ServiceRecord.joins(:engine).where(engines: { user_id: current_user.id }).order('date DESC')
    @managed_tracks = current_user.managed_tracks.includes(:events)
    @managed_championships = current_user.managed_championships.includes(:events)
  end

  def check
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])
    events = Event.where(id: current_user.followed_events.select(:id))
    .or(Event.where(championship: @followed_championships))

    render json: (start_date..end_date).map { |date|
      {
        date: date,
        events: events.any? { |e| e.start_date <= date && e.end_date >= date }
      }
    }
  end
end

app/views/dashboard/index.html.erb
  <div class="grid grid-cols-12 md:gap-6 gap-4 mt-4 px-4 container mx-auto mb-24">
    <% if current_user.admin? %>
      <div class="col-span-12 rounded-lg shadow-sm border border-slate-200 bg-white dark:bg-slate-800 dark:border-none p-4">
      <div class="flex items-start space-x-3">
        <div class="rounded-full w-10 h-10 flex items-center justify-center bg-indigo-50 dark:bg-indigo-600/30">
          <%= icon "flag", classes: "w-5 h-5 text-indigo-600 stroke-current dark:text-indigo-300" %>
        </div>
        <div class="flex-1">
          <span class="text-indigo-500 dark:text-indigo-400/90 text-sm font-medium">App Summary</span>
          <div class="items-center mt-1 mb-2">
            <h3 class="h2 tracking-tight">Users - <%= User.all.count %></h3>
            <h3 class="h2 tracking-tight">Tracks - <%= Track.all.count %></h3>
            <h3 class="h2 tracking-tight">Events - <%= Event.all.count %></h3>
            <h3 class="h2 tracking-tight">Championships - <%= Championship.all.count %></h3>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <div
      class="md:col-span-12 lg:col-span-4 col-span-12 rounded-lg shadow-sm border border-slate-200 bg-white dark:bg-slate-800 dark:border-none p-4">
      <div class="flex items-start space-x-3">
        <div class="rounded-full w-10 h-10 flex items-center justify-center bg-indigo-50 dark:bg-indigo-600/30">
          <%= icon "flag", classes: "w-5 h-5 text-indigo-600 stroke-current dark:text-indigo-300" %>
        </div>
        <div class="flex-1">
          <span class="text-indigo-500 dark:text-indigo-400/90 text-sm font-medium">Events this Month</span>
          <div class="flex items-center space-x-2 mt-1 mb-2">
            <h3 class="h2 tracking-tight"><%= current_user.followed_events.where(start_date: Date.today.beginning_of_month..Date.today.end_of_month).count %></h3>
          </div>
          <p class="text-sm text-slate-400">vs last month: <strong
              class="text-slate-600 dark:text-slate-400"><%= current_user.followed_events.where(start_date: Date.today.prev_month.beginning_of_month..Date.today.prev_month.end_of_month).count %></strong></p>
          </p>
        </div>
      </div>
    </div>
    <div
      class="md:col-span-12 lg:col-span-4 col-span-12 rounded-lg shadow-sm border border-slate-200 bg-white dark:bg-slate-800 dark:border-none p-4">
      <div class="flex items-start space-x-3">
        <div class="rounded-full w-10 h-10 flex items-center justify-center bg-yellow-50 dark:bg-yellow-75">
          <%= icon "flag", classes: "w-6 h-6 text-red-600 stroke-current dark:text-red-400/90" %>
        </div>
        <div class="flex-1">
          <span class="text-yellow-100 dark:text-yellow-100 text-sm font-medium">Last Event</span>
          <div class="flex items-center space-x-2 mt-1 mb-1">
            <% if current_user.followed_events.where('end_date < ?', Date.today).order(end_date: :desc).first.present? %>
              <h3 class="h2 tracking-tight"><%= current_user.followed_events.where('end_date < ?', Date.today).order(end_date: :desc).first&.track&.name %></h3>
              <p> - </p>
              <h3 class="h2 tracking-tight"><%= current_user.followed_events.where('end_date < ?', Date.today).order(end_date: :desc).first&.title %></h3>
              <p> - </p>
              <p class="text-green-600"><%= current_user.followed_events.where('end_date < ?', Date.today).order(end_date: :desc).first&.start_date.strftime('%d %B  %Y') %></p>
            <% else %>
              <h3 class="h2 tracking-tight">No Events</h3>
            <% end %>
            
          </div>
          <p class="text-sm text-slate-400">Race Result: <strong
              class="text-slate-600 dark:text-slate-400">Coming Soon</strong></p>
          </p>
        </div>
      </div>
    </div>
    <div
      class="md:col-span-12 lg:col-span-4 col-span-12 rounded-lg shadow-sm border border-slate-200 bg-white dark:bg-slate-800 dark:border-none p-4">
      <div class="flex items-start space-x-3">
        <div class="rounded-full w-10 h-10 flex items-center justify-center bg-red-50 dark:bg-red-500/20">
          <%= icon "flag", classes: "w-6 h-6 text-red-600 stroke-current dark:text-red-400/90" %>
        </div>
        <div class="flex-1">
          <span class="text-red-400 dark:text-red-400/90 text-sm font-medium">Next Event</span>
          <div class="flex items-center space-x-2 mt-1 mb-1">
            <% if current_user.followed_events.where(start_date: Date.today..Date.today.end_of_month).order(:start_date).first.present? %>
              <h3 class="h2 tracking-tight"><%= current_user.followed_events.where(start_date: Date.today..Date.today.end_of_month).order(:start_date).first&.track.name %></h3>
              <p> - </p>
              <h3 class="h2 tracking-tight"><%= current_user.followed_events.where(start_date: Date.today..Date.today.end_of_month).order(:start_date).first&.title %></h3>
              <p> - </p>
              <p class="text-green-600"><%= current_user.followed_events.where(start_date: Date.today..Date.today.end_of_month).order(:start_date).first&.start_date&.strftime("%b %d, %Y") %></p>
            <% else %>
              <h3 class="h2 tracking-tight">No Events</h3>
            <% end %>
          </div>
          <p class="text-sm text-slate-400">Last Result Here: <strong
              class="text-slate-600 dark:text-slate-400">Coming Soon</strong></p>
          </p>
        </div>
      </div>
    </div>
    


    <div
      class="lg:col-span-6 md:cols-span-12 col-span-12 rounded-lg shadow-sm border border-slate-200 bg-white dark:bg-slate-800 dark:border-none p-6">
      <div class="flex items-center justify-between mb-4">
        <h4 class="text-lg font-medium">Engines</h4>
        <% if respond_to?(:engines_path) %>
          <%= link_to "View all", engines_path, class: "font-medium text-sm hover:text-indigo-600 text-slate-600 dark:text-slate-400 dark:hover:text-indigo-300" %>
        <% else %>
          <%= link_to "Add Engine", new_engines_path, class: "hidden font-medium text-sm hover:text-indigo-600 text-slate-600 dark:text-slate-400 dark:hover:text-indigo-300" %>
        <% end %>
      </div>

      <div class="space-y-4 divide-y dark:divide-slate-600">
      <% @engines.each do | engine | %>
          <%= link_to engine_path(engine), class: "p-2 flex flex-wrap items-center group" do %>
            <div class="md:flex-1 md:block flex justify-between w-full">
              <div class="flex items-center space-x-3">
                <p class="font-medium hover:text-indigo-600 flex-1"><%= engine.name %></p>
              </div>
              <div class="text-left">
                <span class="bg-green-100 text-green-800 font-medium px-2 py-1 leading-tight text-xs inline-block sm:mb-0 rounded md:ml-9 dark:bg-green-500/20 dark:text-green-300/80">Engine Number - <%= engine.engine_number %></span>
              </div>
            </div>

            <div
              class="md:text-right text-left md:group-hover:-translate-x-1 md:group-hover:transition duration-200 md:group-hover:transform md:w-auto w-full md:pt-0 pt-3">
              <p class="font-medium text-slate-600 dark:text-slate-300">Current Seal: <%= engine.seal_number %></p>
              <p class="text-xs text-slate-500 dark:text-slate-400">Last Service Date: <%= engine.service_records.last&.date || 'No service records available' %>
 </p>
            </div>
            <div
              class="opacity-0 group-hover:opacity-100 transition ease-in-out group-hover:transform group-hover:translate-x-1 md:block hidden">
              <%= icon "chevron-right", classes: "w-4 h-4 stroke-current text-slate-500 group-hover:text-indigo-600 dark:group-hover:text-indigo-300" %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="mt-4"> 
        <%= link_to "Add New Engine", new_engine_path, class: "btn btn-white" %>
      </div>
    </div>

    <div
      class="lg:col-span-6 md:cols-span-12 col-span-12 rounded-lg shadow-sm border border-slate-200 bg-white dark:bg-slate-800 dark:border-none p-6">
      <div class="flex items-center justify-between mb-4">
        <h4 class="text-lg font-medium">Engine Service Records</h4>
      </div>

      <div class="space-y-4 divide-y dark:divide-slate-600">
      <% @service_records.each do | record | %>
          <%= link_to engine_service_record_path(record.engine, record), class: "p-2 flex flex-wrap items-center group" do %>
            <div class="md:flex-1 md:block flex justify-between w-full">
              <div class="flex items-center space-x-3">
                <p class="font-medium hover:text-indigo-600 flex-1"><%= record.engine.name %></p>
              </div>
              <div class="text-left">
                <span class="bg-green-100 text-green-800 font-medium px-2 py-1 leading-tight text-xs inline-block sm:mb-0 rounded md:ml-9 dark:bg-green-500/20 dark:text-green-300/80">Engine Number - <%= record.engine.engine_number %></span>
              </div>
            </div>

            <div
              class="md:text-right text-left md:group-hover:-translate-x-1 md:group-hover:transition duration-200 md:group-hover:transform md:w-auto w-full md:pt-0 pt-3">
              <p class="font-medium text-slate-600 dark:text-slate-300">Current Seal: <%= record.new_seal_number %></p>
              <p class="text-xs text-slate-500 dark:text-slate-400">Last Service Date: <%= record.date %></p>
            </div>
            <div
              class="opacity-0 group-hover:opacity-100 transition ease-in-out group-hover:transform group-hover:translate-x-1 md:block hidden">
              <%= icon "chevron-right", classes: "w-4 h-4 stroke-current text-slate-500 group-hover:text-indigo-600 dark:group-hover:text-indigo-300" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    
       <div
      class="p-6 lg:col-span-12 md:col-span-12 col-span-12 rounded-lg shadow-sm border border-slate-200 bg-white dark:bg-slate-800 dark:border-none dark:text-slate-300">
        <div id="calendar-section" class="mb-6">
        <div class="flex items-center justify-between mb-4">
              <h4 class="font-medium text-slate-800 dark:text-slate-300 tracking-tight text-xl m-0">Calendar</h4>
              <%= link_to "View all Events", "#", class: "font-medium text-sm hover:text-indigo-600 text-slate-600 dark:text-slate-400 dark:hover:text-indigo-300" %>
            </div>          
          <%= turbo_frame_tag :calendar, src: calendars_path(date: Date.today) %>
        </div>
    </div>   
  </div>

app/views/dashboard/old_dash.html.erb
<div class="bg-gray-100 min-h-screen pt-8">
  <div class="container mx-auto px-4">

    <div class="mb-10">
      <h1 class="text-4xl font-bold text-gray-800 text-center">Dashboard</h1>
      <% if current_user.role == 'manager' %>
        <p class="text-gray-600 text-center">Welcome to your Dashboard. Here you can manage your Track, Events and Championships.</p>
      <% elsif current_user.admin? %>
        <p class="text-gray-600 text-center">Admin Dashboard</p>
      <% else %>
        <p class="text-gray-600 text-center">Welcome to your Dashboard. Here you can view your Tracks, Championships and Events.</p>
      <% end %>
    </div>

    <% if current_user.admin? %>
      <div class="mb-6">
        <h2 class="text-2xl font-semibold text-gray-700 mb-4">Admin</h2>
        <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          <div class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">App Stats</h5>
            <p class="text-white-600"><%= User.all.count %><strong> - Users</strong></p>
            <p class="text-white-600"><%= Track.all.count %><strong> - Tracks</strong></p>
            <p class="text-white-600"><%= Event.all.count %><strong> - Events</strong></p>
            <p class="text-white-600"><%= Championship.all.count %><strong> - Championships</strong></p>
          </div>
        </div>
      </div>
    <% end %>
  
    <% if current_user.role == 'manager' %>
      <div class="mb-6">
        <h2 class="text-2xl font-semibold text-gray-700 mb-4">Manage</h2>
        <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          <% @managed_tracks.each do |track| %>
            <div class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
              <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= track.name %></h5>
              <%= link_to edit_track_path(track), class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-green-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-green-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
                Edit Track
              <% end %>
              <%= link_to track_path(track), class: "mt-4 inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
                View Track
              <% end %>
            </div>
          <% end %>
           <div class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Events</h5>
          <div class="mb-6">
            <% if @managed_tracks.empty? %>
              <p class="text-gray-600">You are not managing any tracks or events yet.</p>
            <% else %>
              <% @managed_tracks.each do |track| %>
                <% if track.events.any? %>
                  <h6 class="text-xl font-bold text-gray-900 mt-4 mb-2 dark:text-white"><%= track.name %></h6>
                  <ul class="divide-y divide-gray-200 dark:divide-gray-700">
                    <% track.events.each do |event| %>
                      <li class="py-4 flex justify-between items-center">
                        <%= link_to event.title, event_path(event), class: "text-white hover:text-blue-600 font-medium" %>
                        <div>
                          <%= link_to 'View', event_path(event), class: "inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
                          <%= link_to 'Edit', edit_event_path(event), class: "ml-2 inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" %>
                        </div>
                      </li>
                    <% end %>
                  </ul>
                <% else %>
                  <p class="text-gray-600">No events found for <%= track.name %>.</p>
                <% end %>
              <% end %>
            <% end %>
            <%= link_to new_event_path, class: "mt-4 inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
              Create event
            <% end %>
          </div>
        </div>
          <div class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Championships</h5>
            <div class="mb-6">
              <% if @managed_championships.empty? %>
                <p class="text-gray-600">You are not managing any championships yet.</p>
              <% else %>
                <ul class="divide-y divide-gray-200 dark:divide-gray-700">
                  <% @managed_championships.each do |championship| %>
                    <li class="py-4 flex justify-between items-center">
                      <%= link_to championship.name, championship_path(championship), class: "text-white hover:text-blue-600 font-medium" %>
                      <div>
                        <%= link_to 'View', championship_path(championship), class: "inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
                        <%= link_to 'Edit', edit_championship_path(championship), class: "ml-2 inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" %>
                      </div>
                    </li>
                  <% end %>
                </ul>
              <% end %>
              <%= link_to new_championship_path, class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
              Create Championship
            <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="mb-6 mt-6">
      <h2 class="text-2xl font-semibold text-gray-700 mb-4">My Tracks</h2>
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
      <% if @followed_tracks.empty? %>
        <p class="text-gray-600">You are not following any tracks yet.</p>
      <% end %>
        <% @followed_tracks.each do |track| %>
          <div class="bg-white rounded-lg shadow-lg flex">
            <div class="flex-none w-1/3">
              <%= image_tag(track.main_image, alt: track.name, class: "object-cover h-full w-full rounded-l-lg") if track.main_image.present? %>
            </div>
            <div class="p-4 flex-grow">
            <h3 class="font-semibold text-lg text-blue-800 mb-2 h-fit">
              <%= link_to track.name, track_path(track) %>
            </h3>
            <p class="text-gray-600"><strong>Location</strong> - <%= track.location %></p>
            <p class="text-gray-600"><strong>Next Test Day </strong> - <% next_event = track.events.where(event_type: 'Test').order(start_date: :asc).find { |event| event.start_date >= Date.today } %>
            <% if next_event.present? %>
              <%= next_event.title %> on <%= next_event.start_date.strftime("%B %d, %Y") %>
            <% else %>
              No Upcoming Test Days
            <% end %></p>
            <p class="text-gray-600"><strong>Next Race </strong><% next_event = track.events.where(event_type: 'Race').order(start_date: :asc).find { |event| event.start_date >= Date.today } %>
            <% if next_event.present? %>
              <%= next_event.title %> on <%= next_event.start_date.strftime("%B %d, %Y") %>
            <% else %>
              No Upcoming Race Days
            <% end %></p>
            <div class="flex mt-4">
              <%= link_to track_path(track), class: "btn btn-primary" do %>
                View
              <% end %>
          </div>
            </div>
            </div>
        <% end %>
      </div>
    </div>

    <div class="mb-6">
      <h2 class="text-2xl font-semibold text-gray-700 mb-4">My Championships</h2>
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <% if @followed_championships.empty? %>
          <p class="text-gray-600">You are not following any championships yet.</p>
        <% end %>
        <% @followed_championships.each do |championship| %>
          <div class="bg-white rounded-lg shadow-lg flex">
            <div class="flex-none w-1/3">
            <% if championship.image.present? %>
              <%= image_tag(championship.image, alt: championship.name, class: "object-cover h-full w-full rounded-l-lg") if championship.image.present? %>
            <% else %>
              <%= image_tag random_default_image, alt: championship.name, class: "object-cover h-full w-full rounded-l-lg" %>
            <% end %>
            </div>
            <div class="p-4 flex-grow">
            <h3 class="font-semibold text-lg text-blue-800 mb-2">
              <%= link_to championship.name, championship_path(championship) %>
            </h3>
              <p class="text-gray-600"><strong>Next Race:</strong> <%= championship.next_champ_event.title %>: <%= championship.next_champ_event.start_date.strftime("%B %d, %Y") %></p>
              <p class="text-gray-600 mt-4"><strong>at</strong> <%= championship.next_champ_event.track.name %></p>
              <div class="flex mt-4">
                  <%= link_to championship_path(championship), class: "rounded border-2 border-gray-400 px-7 pb-[8px] pt-[10px] text-sm font-medium uppercase leading-normal text-gray-700 transition duration-150 ease-in-out hover:border-neutral-100 hover:bg-gray-600 hover:text-neutral-100 focus:border-neutral-100 focus:text-neutral-100 focus:outline-none focus:ring-0 active:border-neutral-200 active:text-neutral-200" do %>
                    View
                  <% end %>
                </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="mb-6">
      <h2 class="text-2xl font-semibold text-gray-700 mb-4">Your Next Events...</h2>
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <% if @timeline_events.empty? %>
          <p class="text-gray-600">You have nothing planned this weeekend...</p>
        <% end %>
        <% @timeline_events.each do |event| %>
          <div class="bg-white rounded-lg shadow-lg flex">
            <div class="flex-none w-1/3">
            <% if event.image.attached? %>
              <%= image_tag(event.image, alt: event.title, class: "object-cover h-full w-full rounded-l-lg") %>
            <% else %>
              <%= image_tag random_default_image, alt: event.title, class: "object-cover h-full w-full rounded-l-lg" %>
            <% end %>
            </div>
            <div class="p-4 flex-grow">
            <h3 class="font-semibold text-lg text-blue-800 mb-2">
            <% if event.championship.present? %>
              <%= link_to event.championship.name, event_path(event) %> -
            <% end %>
              <%= link_to event.title, event_path(event) %>
            </h3>
            <p class="text-gray-600 mb-4"><strong>Date:</strong> <%= event.start_date.strftime("%B %d, %Y") %></p>
            <p class="text-gray-600 mb-4"><strong>Track:</strong> <%= (event.track&.name || 'No track assigned').truncate(20) %></p>
            <% if event.championship.present? %>
            <p class="text-gray-600"><strong>Championship:</strong> <%= event.championship.name %></p>
                <div class="flex mt-4">
                  <%= link_to event_path(event), class: "rounded border-2 border-gray-400 px-7 pb-[8px] pt-[10px] text-sm font-medium uppercase leading-normal text-gray-700 transition duration-150 ease-in-out hover:border-neutral-100 hover:bg-gray-600 hover:text-neutral-100 focus:border-neutral-100 focus:text-neutral-100 focus:outline-none focus:ring-0 active:border-neutral-200 active:text-neutral-200" do %>
                    View
                  <% end %>
                </div>
            <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  <div id="calendar-section" class="mb-6">
    <h2 class="text-2xl font-semibold text-gray-600 text-center">My Calendar</h2>
    <p class="text-gray-700 text-center text-sm">Click a date to see what's happening</p>  
    <%= turbo_frame_tag :calendar, src: calendars_path(date: Date.today) %>
  </div>
</div>