config/routes.rb
Rails.application.routes.draw do

	root action: :home, controller: "page"
	get 'privacy', to: 'page#privacy'
	get 'about', to: 'page#about'
	get 'home', to: 'page#home'
	get 'cookie', to: 'page#cookie'

	resources :dashboard, only: [:index] do
		collection do
			get :check
		end
	end

	resources :engines do
		resources :service_records do
			member do
				delete :remove_engine_service_record_image, to: 'service_records#remove_image', as: :remove_image
			end
		end
		member do
			delete :remove_image
		end
	end

	resources :events do
		collection do
			get :check
		end
	end

	namespace :api do
    namespace :v1 do
      resources :events, only: [:index, :show]
    end
  end

	resources :tracks do
		collection do
			get :search
		end
	end

	devise_for :users
	resources :contacts, only: [:new, :create]
	resources :championships
	resource :calendars, only: [:show]
	resources :follows, only: [:create, :destroy]

	get '*unmatched_route', to: 'application#not_found', constraints: lambda { |req|
		req.path.exclude? 'rails/active_storage'
	}

	if Rails.env.development? || Rails.env.test?
		mount Railsui::Engine, at: "/railsui"
	end
end

app/models/engine.rb
class Engine < ApplicationRecord
  belongs_to :user
  has_many :service_records, dependent: :nullify
  has_many_attached :engine_images
  has_one_attached :logbook_cover

  validates :name, :engine_number, :engine_make, :engine_model, :year_manufactured, :barrel_number, :seal_number, presence: true

  def display_name
    "#{name} - #{engine_number}"
  end
end 

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_engine, only: [:show, :edit, :update, :destroy]
  before_action :authorize_engine, only: [:show, :edit, :update, :destroy]

  def new
    @engine = Engine.new
    authorize @engine
  end

  def create
    @engine = Engine.new(engine_params)
    @engine.user = current_user
    authorize @engine
    if @engine.save
      redirect_to engine_path(@engine), notice: 'Engine added successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def index
    @engines = current_user.engines
    @all_engines = Engine.all
  end

  def edit
  end

  def update
    if @engine.update(engine_params.except(:engine_photos, :existing_photos))
      # Update the enging photos to upload with a background job
      redirect_to @engine, notice: 'Engine was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @engine.destroy
    redirect_to engines_path, notice: 'Engine deleted successfully'
  end

  # This needs to be tested and improved to see if removing images live from the form has a better option
  def remove_image
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge_later
    redirect_to edit_engine_path(@image.record), notice: 'Image removed successfully'
  end

  private

  def engine_params
    params.require(:engine).permit(:name, :engine_number, :engine_make, :engine_model, :barrel_number, :seal_number, :year_manufactured, :notes, :logbook_cover, engine_images: [], dyno_sheet: [])
  end

  def set_engine
    @engine = Engine.find(params[:id])
  end

  def authorize_engine
    authorize @engine
  end
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/views/engines/_form.html.erb
<div class="max-w-screen-lg mx-auto">
  <%= form_with(model: @engine, local: true, html: { enctype: 'multipart/form-data' }) do |form| %>
    <% if @engine.errors.any? %>
      <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative my-5" role="alert">
        <strong class="font-bold">Oops!</strong>
        <span class="block sm:inline"> <%= pluralize(@engine.errors.count, "error") %> prohibited this engine from being saved:</span>

        <ul class="list-disc list-inside">
        <% @engine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-4">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-input" %>
    </div>

    <div class="mb-4">
      <%= form.label :engine_make, class: "form-label" %>
      <%= form.text_field :engine_make, class: "form-input" %>
    </div>

     <div class="mb-4">
      <%= form.label :engine_model, class: "form-label" %>
      <%= form.text_field :engine_model, class: "form-input" %>
    </div>

    <div class="mb-4">
      <%= form.label :engine_number, class: "form-label" %>
      <%= form.text_field :engine_number, class: "form-input" %>
    </div>

    <div class="mb-4">
      <%= form.label :barrel_number, class: "form-label" %>
      <%= form.text_field :barrel_number, class: "form-input" %>
    </div>

    <div class="mb-4">
      <%= form.label :seal_number, class: "form-label" %>
      <%= form.text_field :seal_number, class: "form-input" %>
    </div>

    <div class="mb-4">
      <%= form.label :year_manufactured, class: "form-label" %>
      <%= form.text_field :year_manufactured, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= form.label :notes, class: "form-label" %>
      <%= form.text_area :notes, class: "form-input" %>
    </div>
    
    <div class="form-group">
      <%= form.label :engine_image, class: "form-label" %>

      <% if @engine.engine_images.attached? %>
        <% @engine.engine_images.each do |image| %>
          <%= form.hidden_field :engine_images, multiple: true, value: image.signed_id %>
          <%= image_tag image, class: "w-24 h-24 object-cover rounded-lg" %>
          <%= link_to "Remove", remove_image_engine_path(image), data: { confirm: "Are you sure?", turbo_method: :delete }, class: "btn btn-danger" %>
        <% end %>
      <% end %>

      <%= form.file_field :engine_images, multiple: true, class: "form-file" %>
    </div>
    
    <div class="form-group">
      <%= form.label :logbook_cover, class: "form-label" %>
      <%= form.file_field :logbook_cover, class: "form-file" %>
    </div>

    <div class="flex items-center justify-between">
      <%= form.submit "Save Engine", class: "btn btn-white" %>
    </div>



  <% end %>
</div>

app/views/engines/edit.html.erb
<% content_for :title, 'Edit Engine' %>
<div class="text-center mx-auto">
  <h1 class="text-3xl font-bold mx-auto">Edit Engine</h1>
</div>

<div class="container mx-auto px-4">
  <%= render partial: "engines/form" %>
</div>

app/views/engines/index.html.erb
<% content_for :title, 'Your Engines' %>
<div class="bg-gray-100 min-h-screen">
<div class="bg-gray-100 text-center mx-auto pt-8">
  <h1 class="text-3xl font-bold mx-auto text-gray-700">Your Engines</h1>
  <% if @engines.empty? %>
    <p class="text-lg">You have no engines yet. <a href="<%= new_engine_path %>">Create one</a></p>
  <% else %>
  <div class="container mx-auto mt-4">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    </div>
  <% end %>
</div>
</div>

<div class="bg-gray-100 pt-8">
  <div class="container mx-auto px-4">

  <div class="mb-6 ">
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <% if @engines.empty? %>
          <p class="text-gray-600">You have no engines added yet.</p>
        <% else %>
          <% @engines.each do |engine| %>
            <div class="bg-white rounded-lg shadow-lg flex">
              <div class="flex-none w-1/3">
                <%= image_tag(engine.engine_images.first, alt: engine.name, class: "object-contain rounded-l-lg") if engine.engine_images.present? %>
              </div>
              <div class="p-4 w-2/3">
                <h3 class="font-semibold text-lg text-blue-800 mb-2">
                  <%= link_to engine.name, engine_path(engine) %>
                </h3>
                <p class="text-gray-600"><strong>Make:</strong> <%= engine.engine_make %></p>
                <p class="text-gray-600"><strong>Model:</strong> <%= engine.engine_model %></p>
                <p class="text-gray-600"><strong>Year:</strong> <%= engine.year_manufactured %></p>
                <p class="text-gray-600"><strong>Barrel Number:</strong> <%= engine.barrel_number %></p>
                <p class="text-gray-600"><strong>Last Rebuild Date:</strong> </p>
              </div>
              
              <div class="flex items-center justify-center">
              </div>
            </div>
          <% end %>
        <% end %>
          <%= link_to "Add Engine", new_engine_path, class: "btn btn-primary text-white" %>
      </div>
  </div>
</div>
</div>


<% if current_user.admin? %>
    <div class="md:py-6 py-6 px-4 bg-gray-100">
      <div class="pb-6 container mx-auto">
        <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-6 py-3">
                Engine Name
              </th>
              <th scope="col" class="px-6 py-3">
                Engine Number
              </th>
              <th scope="col" class="px-6 py-3">
                Engine Make
              </th>
              <th scope="col" class="px-6 py-3">
                View
              </th>
            </tr>
          </thead>

          <tbody>
            <% @all_engines.each do |engine| %>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
              <td class="px-6 py-4">
                <%= engine.name %>
              </td>
              <td class="px-6 py-4">
                <%= engine.engine_number %>
              </td>
              <td class="px-6 py-4">
                <%= engine.engine_make %>
              </td>
              <td class="px-6 py-4">
                <%= link_to "View", engine_path(engine), class: "btn btn-primary text-white" %>
              </td>
            <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
<% end %>
</div>

app/views/engines/new.html.erb
<% content_for :title, 'New Engine' %>
<div class="text-center mx-auto">
  <h1 class="text-3xl font-bold mx-auto">New Engine</h1>
</div>

<div class="container mx-auto px-4">
  <%= render partial: "engines/form" %>
</div>

app/views/engines/show.html.erb
<div class="md:pb-6 pb-6 pt-16 md:pt-16 px-4">
  <div class="container mx-auto">
    <nav class="font-heading text-sm mb-6 text-zinc-700 dark:text-zinc-300">
      <ul class="flex items-center space-x-3">
        <li class="after:content-['/'] after:relative after:text-zinc-300 after:left-1 dark:after:text-zinc-500">
          <%= link_to "Engines", (defined?(engines_path) ? engines_path : "#"), class: "text-primary-600 hover:text-primary-700 dark:text-primary-500 dark:hover:text-primary-600" %>
        </li>
        <li>
          <p><%= @engine.name %></p>
        </li>
      </ul>
    </nav>
    <div class="flex flex-wrap items-center justify-between pb-6 md:pb-0">
      <div class="flex items-center space-x-3 mb-6 flex-1">
        <% if @engine.engine_images.attached? %>
          <%= image_tag @engine.engine_images.first, alt: "Engine image", class: "w-16 h-16 rounded-full border-2 border-white" %>
        <% else %>
          <%= image_tag "https://via.placeholder.com/150", alt: "Engine image", class: "w-16 h-16 rounded-full border-2 border-white" %>
        <% end %>
        <div>
          <h1 class="pb-1 text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight"><%= @engine.name %></h1>
          <div class="text-sm text-zinc-600 pl-1 pb-1 dark:text-zinc-400">
            <%= link_to "View All Engines", engines_path, class: "text-primary-600 hover:text-primary-700 dark:text-primary-500 dark:hover:text-primary-600" %>
          </div>
        </div>
      </div>
      <div class="flex md:justify-end space-x-3 md:w-auto w-full">
        <% if current_user.admin? %>
          <%= link_to "Back to Dashboard", dashboard_index_path, class: "btn btn-white" %>
          <%= link_to "Edit Engine", edit_engine_path(@engine), class: "btn btn-white" %>
          <%= link_to "Delete Engine", engine_path(@engine), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" }, class: "btn bg-red-700" %>
        <% elsif current_user == @engine.user %>
          <%= link_to "Back to Dashboard", dashboard_index_path, class: "btn btn-white" %>
          <%= link_to "Edit Engine", edit_engine_path(@engine), class: "btn btn-white" %>
        <% end %>
      </div>
    </div>
  </div>

<div class="container mx-auto px-4 py-6">
  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    
    <!-- Engine Gallery Section -->
    <div class="container mx-auto relative" data-controller="engine-gallery">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <% displayed_images = 0 %>
        <!-- Render up to 4 photos -->
        <% if @engine.engine_images.attached? && @engine.engine_images.any? %>
          <% @engine.engine_images.limit(4).each do |image| %>
            <%= image_tag url_for(image), class: 'lg:h-72 h-72 w-full object-cover rounded-lg' %>
            <% displayed_images += 1 %>
          <% end %>
        <% end %>

        <!-- Message for non-owners if there are no images -->
        <% if displayed_images == 0 %>
          <div class="lg:h-72 h-72 bg-gray-500 rounded-lg flex items-center justify-center text-center text-white text-lg">
            No images available
          </div>
        <% end %>
      </div>
    </div>

    <!-- Engine Details Section -->
    <div class="container mx-auto">
      <div class="pb-6">
        <h1 class="text-center pb-1 text-2xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight"><%= @engine.name %></h1>
      </div>
      <div class="grid grid-cols-2 md:grid-cols-2 gap-x-6 gap-y-8">
        <% details = [
          { icon: "folder", label: "Make", value: @engine.engine_make.capitalize },
          { icon: "folder", label: "Model", value: @engine.engine_model.capitalize },
          { icon: "calendar", label: "Engine Number", value: @engine.engine_number },
          { icon: "calendar", label: "Year", value: @engine.year_manufactured },
          { icon: "wrench", label: "Last Service", value: @engine.service_records.any? ? @engine.service_records.last.date.strftime("%d %b %y") : "No Record" },
          { icon: "identification", label: "Barrel Number", value: @engine.barrel_number },
          { icon: "identification", label: "Current Seal", value: @engine.seal_number.present? ? @engine.seal_number : "No Record" },
          { icon: "wrench", label: "Last Serviced by", value: @engine.service_records.any? ? @engine.service_records.last.engine_builder : "No Record" }
        ] %>
        <% details.each do |detail| %>
          <div class="flex flex-col items-start md:ml-24">
            <div class="flex items-start space-x-3">
              <%= icon detail[:icon], classes: "w-5 h-5 text-zinc-500 dark:text-zinc-300" %>
              <p class="font-heading dark:text-zinc-50"><%= detail[:label] %></p>
            </div>
            <span class="pl-8 text-zinc-600 dark:text-zinc-300"><%= detail[:value] %></span>
          </div>
        <% end %>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-8 pt-8">
        <div class="flex flex-col items-start">
          <div class="flex items-center space-x-3">
            <%= icon "pencil-square", classes: "w-5 h-5 text-zinc-500 dark:text-zinc-300" %>
            <p class="font-heading text-lg font-semibold dark:text-zinc-50">Engine Notes</p>
          </div>
          <span class="pl-8 text-zinc-600 dark:text-zinc-300"><%= @engine.notes %></span>
        </div>
      </div>
    </div>
  </div>
</div> 

      <div class="md:py-6 py-6 px-4">
        <div class="pb-6 container mx-auto">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            <div class="mt-5">
              <div class="pb-6">
                <h1 class="pb-1 text-2xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight text-center">Dyno Details</h1>
              </div>

              <% if @engine.service_records.any? %>
                <% last_service_record_with_dyno = @engine.service_records.order(date: :desc).find { |record| record.dyno_sheets.attached? } %>

                <% if last_service_record_with_dyno %>
                  <!-- Determine how many images are present -->
                  <% images = last_service_record_with_dyno.dyno_sheets.first(2) %>

                  <!-- Conditional grid layout -->
                  <div class="<%= images.size == 1 ? 'grid grid-cols-1' : 'grid grid-cols-1 md:grid-cols-2 gap-4' %>">

                    <% images.each do |image| %>
                      <!-- Each image is clickable and conditionally takes full width or half width -->
                      <a href="#!" onclick="openModal('<%= url_for(image) %>')" class="w-full">
                        <%= image_tag url_for(image), class: "rounded-xl object-cover w-full h-48 cursor-pointer" %>
                      </a>
                    <% end %>

                  </div>
                <% else %>
                  <p class="text-center">Add a Service Record with a DynoSheet.</p>
                <% end %>
              <% else %>
                <p class="text-center">No service records to add a DynoSheet.</p>
              <% end %>
            </div>


      <!-- Modal Section -->
      <div id="imageModal" class="hidden fixed inset-0 bg-gray-900 bg-opacity-75 flex items-center justify-center z-50">
        <div class="relative">
          <span onclick="closeModal()" class="absolute top-0 right-0 text-black text-5xl cursor-pointer">&times;</span>
          <img id="modalImage" src="" class="rounded-xl max-w-full max-h-screen">
        </div>
      </div>

      <script>
        function openModal(imageSrc) {
          document.getElementById("modalImage").src = imageSrc;
          document.getElementById("imageModal").classList.remove("hidden");
        }

        function closeModal() {
          document.getElementById("imageModal").classList.add("hidden");
        }
      </script>


      <!-- LogBook Section -->
      <div class="mt-5">
        <div class="pb-6">
          <h1 class="pb-1 text-2xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight text-center">LogBook</h1>
        </div>
        <div class="flex justify-center">
          <% if @engine.logbook_cover.attached? %>
            <%= image_tag @engine.logbook_cover, class: "rounded-xl w-96 object-cover h-96" %>
          <% else %>
            <p class="text-center">No Logbook Cover attached</p>
          <% end %>
        </div>
      </div>
      
    </div>
  </div>
</div>


  <div class="container mx-auto">
   <div class="mt-12 md:mt-5">
            <div class="pb-6">
              <h1 class="pb-1 text-2xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight text-center">Service Records</h1>
            </div>
            <div class="">
                <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">
                                Date
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Seal
                            </th>
                            <th scope="col" class="px-6 py-3">
                                View
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @engine.service_records.each do |service_record| %>
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                            <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                <%= service_record.date.strftime("%d %b %y") %>
                            </td>
                            <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                <%= service_record.new_seal_number %>
                            </td>
                            <td class="px-6 py-4">
                                <%= link_to "View", engine_service_record_path(@engine, service_record), class: "text-primary-600 hover:text-primary-700 dark:text-primary-500 dark:hover:text-primary-600" %>
                            </td>
                        </tr>
                      <% end %>
                    </tbody>
                    <tfoot>
                      <tr>
                        <td colspan="4" class="text-center py-4">
                          <%= link_to "Add New Service Record", new_engine_service_record_path(@engine), class: "bg-primary-600 hover:bg-primary-700 text-white font-bold py-2 px-4 rounded" %>
                        </td>
                      </tr>
                    </tfoot>
                </table>
            </div>
          </div>
  </div>

  </div>
</div>