config/routes.rb
Rails.application.routes.draw do

	root action: :home, controller: "page"
	get 'privacy', to: 'page#privacy'
	get 'about', to: 'page#about'
	get 'home', to: 'page#home'
	get 'cookie', to: 'page#cookie'

	resources :dashboard, only: [:index] do
		collection do
			get :check
		end
	end

	resources :engines do
		resources :service_records do
			member do
				delete :remove_engine_service_record_image, to: 'service_records#remove_image', as: :remove_image
			end
		end
		member do
			delete :remove_image
		end
	end

	resources :events do
		collection do
			get :check
		end
	end

	namespace :api do
    namespace :v1 do
      resources :events, only: [:index, :show]
    end
  end

	resources :tracks do
		collection do
			get :search
		end
	end

	devise_for :users
	resources :contacts, only: [:new, :create]
	resources :championships
	resource :calendars, only: [:show]
	resources :follows, only: [:create, :destroy]

	get '*unmatched_route', to: 'application#not_found', constraints: lambda { |req|
		req.path.exclude? 'rails/active_storage'
	}

	if Rails.env.development? || Rails.env.test?
		mount Railsui::Engine, at: "/railsui"
	end
end

app/views/shared/_email_action.html.erb
<% action_brand_color ||= "primary" %>
<% align ||= "center" %>

<table class="action" align="<%= align %>">
  <tr>
    <td align="<%= align %>">
      <a href="<%= action_path %>" class="action__link  action__link--<%= action_brand_color %>" target="_blank"><%= action %></a>
      <div itemscope itemtype="http://schema.org/EmailMessage">
        <div itemprop="potentialAction" itemscope itemtype="http://schema.org/ViewAction">
          <link itemprop="target" href="<%= action_path %>"/>
          <meta itemprop="name" content="<%= action %>"/>
        </div>
      </div>
    </td>
  </tr>
</table>

app/views/shared/_email_spacer.html.erb
<table class="spacer">
  <tbody>
    <tr>
      <td height="<%= amount %>" style="font-size:<%= amount %>px;line-height:<%= amount %>px;">&nbsp;</td>
    </tr>
  </tbody>
</table>
x

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
<div class="bg-rose-50 text-rose-700 sm:px-9 sm:py-6 px-6 py-6 rounded-lg mb-6 dark:bg-rose-400/10 dark:border dark:border-rose-400/20 dark:text-rose-50 text-sm" role="alert">
  <div class="flex items-start space-x-4">
    <%= icon "shield-exclamation", classes: "w-6 h-6 text-rose-700 flex-shrink-0", variant: :solid %>
    <div class="flex-1">
      <p class="font-bold"><%= pluralize(resource.errors.count, "error") %> prevented this from being completed:</p>
      <ul class="list-disc mt-3 ml-4">
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_event_badges.html.erb
    <% if event.event_type == "Test Day" %>
      <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-200 text-green-900 whitespace-nowrap">
        <svg class="mr-1.5 h-2 w-2 text-green-500" fill="currentColor" viewBox="0 0 8 8">
          <circle cx="4" cy="4" r="3" />
        </svg>
        <%= event.event_type %>
      </span>
    <% elsif event.event_type == "Race" %>
      <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-indigo-200 text-indigo-900 whitespace-nowrap">
        <svg class="mr-1.5 h-2 w-2 text-indigo-500" fill="currentColor" viewBox="0 0 8 8">
          <circle cx="4" cy="4" r="3" />
        </svg>
        <%= event.event_type %>
      </span>
    <% end %>

    <% if event&.licence.present? %>
      <% if event.licence == "MSUK Licence" %>
        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-200 text-blue-900 whitespace-nowrap">
          <svg class="mr-1.5 h-2 w-2 text-blue-500" fill="currentColor" viewBox="0 0 8 8">
            <circle cx="4" cy="4" r="3" />
          </svg>
          <%= event.licence %>
        </span>
      <% elsif event.licence == "Non Licensed" %>
        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-rose-200 text-rose-900 whitespace-nowrap">
          <svg class="mr-1.5 h-2 w-2 text-rose-500" fill="currentColor" viewBox="0 0 8 8">
            <circle cx="4" cy="4" r="3" />
          </svg>
          <%= event.licence %>
        </span>
      <% end %>
    <% end %>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="bg-indigo-600 text-white text-center p-4" role="alert">
    <p><%= sanitize notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="bg-rose-600 text-white text-center p-4" role="alert">
    <p><%= sanitize alert %></p>
  </div>
<% end %>

app/views/shared/_follow_button.html.erb
<%= turbo_frame_tag dom_id(followable, "follow_#{dom_class(followable)}"), class: "w-auto" do %>
  <% if current_user.following?(followable) %>
    <%= link_to "Remove from My #{followable.class.name.pluralize}", follow_path(id: current_user.follows.find_by(followable: followable).id), method: :delete, class: "btn btn-primary bg-rose-600 hover:bg-rose-700", data: { turbo_method: :delete } %>
  <% else %>
    <%= link_to "Add to My #{followable.class.name.pluralize}", follows_path(followable_type: followable.class.name, followable_id: followable.id), method: :post, class: "btn btn-primary", data: { turbo_method: :post } %>
  <% end %>
<% end %>

app/views/shared/_fonts.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

app/views/shared/_footer.html.erb
<footer class="container mx-auto px-4 pb-2">
  <nav role="Utility navigation">
    <ul class="flex items-center justify-center text-center lg:my-6 mb-6 lg:text-base text-lg">
      <li class="py-3 lg:py-0">
        <%= link_to "Features", "#", class: "px-3 py-2 hover:text-indigo-700 dark:hover:text-indigo-500 hidden" %>
      </li>
        <li class="py-3 lg:py-0">
          <%= link_to "About", about_path, class: "px-3 py-2 hover:text-indigo-700  dark:hover:text-indigo-500 hidden" %>
        </li>
    </ul>
  </nav>

  <ul class="flex items-center justify-center space-x-6 mb-6 hidden">
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "facebook", path: "social/facebook.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-indigo-600 dark:group-hover:text-indigo-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "twitter", path: "social/twitter.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-indigo-600 dark:group-hover:text-indigo-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "linkedin", path: "social/linkedin.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-indigo-600 dark:group-hover:text-indigo-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "youtube", path: "social/youtube.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-indigo-600 dark:group-hover:text-indigo-500" %>
      <% end %>
    </li>
  </ul>

  <div class="container mx-auto flex justify-center mb-2 mt-2">
    <%= link_to 'Submit a Correction', new_contact_path, class: "text-xs inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
  <p class="text-center text-slate-600 text-sm">&copy; KartStream All Rights Reserved. - <%= link_to "Privacy Policy", privacy_path, class: "text-slate-400" %>
</footer>

app/views/shared/_hotel_fuel_section.html.erb
<section id ="event-local-info" class="bg-gray-800">
    <div class="container flex flex-wrap mx-auto mt-10">
        <div class="w-full md:w-1/2 px-2 my-4">
      <h2 class="text-2xl font-bold text-white-800 mb-4 text-center">Hotels</h2>
        <% if @hotels.present? && @hotels['features'].present? %>
          <% @hotels['features'].each do |hotel| %>
            <div class="bg-white shadow-lg rounded-lg overflow-hidden mb-2">
              <div class="p-4">
              <h2 class="text-gray-800 text-xl font-semibold mb-2"><%= hotel['text'] %></h2>
              <% place_name_parts = hotel['place_name'].split(', ') %>
              <% address_without_country = place_name_parts[1..-2].join(', ') %>
              <p class="text-gray-600"><%= address_without_country %></p>
              <% if hotel['geometry'] && hotel['geometry']['coordinates'] %>
                <% coords = hotel['geometry']['coordinates'] %>
                <% origin_address = track.address %>
                <a href="https://www.google.com/maps/dir/?api=1&origin=<%= origin_address %>&destination=<%= coords[1] %>,<%= coords[0] %>" target="_blank" rel="noopener noreferrer" class="text-blue-500 hover:text-blue-600">Get Directions</a>
              <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>No hotel information available.</p>
        <% end %>
    </div>
    <div class="w-full md:w-1/2 px-2 my-4">
        <h2 class="text-2xl font-bold text-white-800 mb-4 text-center">Fuel Stations</h2>
        <% if @fuel_stations.present? && @fuel_stations['features'].present? %>
          <% @fuel_stations['features'].each do |station| %>
            <div class="bg-white shadow-lg rounded-lg overflow-hidden mb-2">
              <div class="p-4">
                <h2 class="text-gray-800 text-xl font-semibold mb-2"><%= station['text'] %></h2>
                <% place_name_parts = station['place_name'].split(', ') %>
                  <% address_without_country = place_name_parts[1..-2].join(', ') %>
                  <p class="text-gray-600"><%= address_without_country %></p>
                  <% if station['geometry'] && station['geometry']['coordinates'] %>
                    <% coords = station['geometry']['coordinates'] %>
                    <% origin_address = track.address %>
                  <a href="https://www.google.com/maps/dir/?api=1&origin=<%= origin_address %>&destination=<%= coords[1] %>,<%= coords[0] %>" target="_blank" rel="noopener noreferrer" class="text-blue-500 hover:text-blue-600">Get Directions</a>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>No fuel station information available.</p>
        <% end %>
    </div>
</section>

app/views/shared/_meta.html.erb
<%#

Put a favicon.ico or favicon.svg (preferred) in your public/ folder and add favicon_link_tag "favicon.svg" to your layout inside the <head></head> tags.

You may optionally reach for the meta_tags gem as I did below and do this all dynamically.

Below are the recommended tags to include for best discoverability between apps and services. You don't need everything listed to see success but many apps now query open graph tags to find assets and content for link previews so it goes a long way (i.e., Slack, Twitter, Facebook).

Generate icons:
https://redketchup.io/favicon-generator (generate from an image)

Tip: Before generating icons, I typically start with a icon that is atleast 512x512 in size. It can have a transparent background (.png, .svg). Keep it as simple as possible.

Free editor/vector tool:
https://figma.com

Previewing:
https://www.opengraph.xyz/


# Usage:

Title:
Change the title and description tags below to match your own site. The title displays alongside your site name in a given browser tab next to the favicon.

Description:
The description is a good place for one to two sentences describing a page OR what the site is all about. You can tweak this on a per-page basis inside your views or controllers. See the metatags gem documentation on tips for doing so: https://github.com/kpumuk/meta-tags#mirrored-values

Images:
Swap your own images for placeholder ones inside the "assets/images/meta" folder Rails UI copied to your app (jpg, png).
%>

<%= display_meta_tags(
  site: "#{Railsui.config.application_name.parameterize}.com", # <!-- change -->,
  reverse: true,
  viewport: "width=device-width, initial-scale=1",
  title: "KartStream",
  canonical: request.original_url,
  og: {
    title: Railsui.config.application_name,
    type: "website",
    url: request.original_url,
    image: [{
      _: image_url("meta/opengraph.jpg"),
      width: 1200,
      height: 630
    }],
    site_name: "#{Railsui.config.application_name.parameterize}.com", # <!-- change -->
    description: "KartStream - The best place to find UK karting events and news.",
  },
  twitter: {
    title: :title,
    description: :description,
    card:  "summary",
    image: {
      _: image_url("meta/opengraph-mark.jpg"),
      width:  400,
      height: 400,
    }
  },
  author: Railsui.config.application_name,
  description: "KartStream",
  icon: [
    {
      href: image_url("meta/favicon.svg"),
      sizes: 'any',
      type: "image/svg+xml"
    },
    {
      href: image_url("meta/favicon-16x16.png"),
      sizes: "16x16",
      type: "images/png"
    },
    {
      href: image_url("meta/android-chrome-192x192.png"),
      sizes: '192x192',
      type: "image/png"
    },
    {
      href: image_url("meta/android-chrome-512x512.png"),
      sizes: '512x512',
      type: "image/png"
    },
    {
      href: image_url("meta/apple-touch-icon.png"),
      sizes: '180x180',
      type: "image/png"
    }
  ])
  %>

app/views/shared/_nav.html.erb
<header class="relative bg-slate-900 border-slate-700" data-controller="nav">
  <%= render "shared/nav_menu" %>
</header>

app/views/shared/_nav_links.html.erb
<li >
  <%= nav_link_to "Home", send("home_path"), class: "nav-link" %>
</li>
<li >
  <%= nav_link_to "Events", send("events_path"), class: "nav-link" %>
</li>
<li >
  <%= nav_link_to "Tracks", send("tracks_path"), class: "nav-link" %>
</li>
<li>
  <%= nav_link_to "Championships", send("championships_path"), class: "nav-link" %>
</li>
<li >
  <%= nav_link_to "Contact", send("new_contact_path"), class: "nav-link" %>
</li>

app/views/shared/_nav_menu.html.erb
<div class="container mx-auto px-4">
  <div class="lg:flex items-center flex-wrap sm:space-x-2">
    <div class="lg:block flex items-center justify-between">
      <%= link_to root_path, class: "w-12 h-12 flex justify-center" do %>
        <svg
          class="fill-current w-5 h-auto text-indigo-600 duration-300 transition ease-in-out
          hover:text-indigo-500"
          width="39" height="50" viewBox="0 0 39 50" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" clip-rule="evenodd"
            d="M8.55264 0C3.82915 0 0 3.82915 0 8.55265V26.1842C0 30.9077 3.82915 34.7368 8.55264 34.7368C13.2761 34.7368 17.1053 30.9077 17.1053 26.1842V8.55264C17.1053 3.82915 13.2761 0 8.55264 0ZM29.6053 0C24.8818 0 21.0527 3.82915 21.0527 8.55264V41.4474C21.0527 46.1709 24.8818 50 29.6053 50C34.3288 50 38.1579 46.1708 38.1579 41.4474V8.55264C38.1579 3.82915 34.3288 0 29.6053 0Z" />
        </svg>
        <span class="sr-only"><%= Railsui.config.application_name %></span>
      <% end %>

      <button
        id="dropdowns-nav-toggle"
        data-action="click->nav#toggle"
        class="lg:hidden block p-1 rounded focus:ring-4 active:bg-white group focus:bg-white/50 focus:bg-slate-800 dark:focus:ring-slate-700">
        <div role="none" data-nav-target="menuBars">
          <%= icon "bars-3-center-left", classes: "w-8 h-8 text-slate-600 group-focus:text-indigo-600
          dark:text-slate-400 dark:group-focus:text-slate-100" %>
        </div>
        <div role="none" data-nav-target="menuCross" class="hidden">
          <%= icon "x-mark", classes: "w-8 h-8 text-slate-400 group-focus:text-slate-100" %>
        </div>
      </button>

    </div>
    <div
      id="dropdowns-navigation"
      class="lg:flex-1 lg:block hidden lg:static absolute top-12 left-0 w-full bg-slate-900 lg:bg-transparent transform origin-top px-4 pb-4 lg:p-0  rounded-b lg:shadow-none shadow-xl z-40 text-base"
      data-nav-target="nav"
      data-transition-enter-active="transition ease-out duration-200"
      data-transition-enter-from="opacity-0 scale-95"
      data-transition-enter-to="opacity-100 scale-100"
      data-transition-leave-from="opacity-100 scale-100"
      data-transition-leave-active="transition ease-in duration-200"
      data-transition-leave-to="opacity-0 scale-95">
      <div
        class="lg:flex-1 lg:flex flex-wrap items-center justify-between lg:text-left text-center">
        <nav role="Primary navigation">
          <ul
            class="lg:flex block items-center flex-wrap space-x-0 lg:space-x-3 lg:text-base  lg:leading-normal leading-relaxed space-y-1 lg:space-y-0 lg:mb-0 mb-2">
            <%= render "shared/nav_links" %>
          </ul>
        </nav>

        <nav role="Secondary navigation">
          <ul class="lg:flex flex-wrap items-center lg:justify-center justify-between lg:space-x-4">
            <% if user_signed_in? %>
              <li class="lg:mt-0 mt-4 flex flex-col items-center relative" data-controller="dropdown">
                <button class="group" type="button" data-action="click->dropdown#toggle click@window->dropdown#hide">
                    <li class="lg:pl-3 w-full lg:w-auto col-span-2">
                      <button id="profile-button" class="group" type="button" data-action="click->dropdown#toggle click@window->dropdown#hide">
                        <%= image_tag 'image1.jpg' , class: "rounded-full lg:w-10 w-12 lg:h-10 h-12 object-cover border-2 border-transparent group-hover:border-indigo-600 transition duration-300 ease-in-out" %>
                      </button>

                      <div class="hidden transition transform origin-to-right lg:absolute right-0 top-10 bg-white rounded-lg lg:shadow-xl lg:shadow-slate-900/10 lg:border border-slate-200 lg:min-w-[200px] z-50 py-1 divide-y lg:w-auto w-full lg:text-sm dark:bg-slate-700 dark:shadow-slate-900/50 dark:border-slate-500/60 text-base font-medium text-slate-200 dark:divide-gray-600" data-dropdown-target="menu"
                        data-transition-enter-from="opacity-0 scale-95"
                        data-transition-enter-to="opacity-100 scale-100"
                        data-transition-leave-from="opacity-100 scale-100"
                        data-transition-leave-to="opacity-0 scale-95">
                        <div role="none">
                          <%= link_to "Edit account", edit_user_registration_path, class: "px-4 py-2 lg:py-[.4rem] hover:text-indigo-600 dark:hover:text-indigo-400 block", data: { turbo: false } %>
                        </div>
                        <div role="none">
                          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "px-4 py-2 lg:py-[.4rem] hover:text-indigo-600 dark:hover:text-indigo-400 block w-full lg:!text-left !text-center", data: { turbo: false  } %>
                        </div>
                      </div>
                    </li>
                   <li class="w-full lg:w-auto lg:mb-0 col-span-2 mb-2">
                      <%= link_to "My Dashboard", dashboard_index_path, class: "btn btn-dark lg:w-auto w-full", data: { turbo: false } %>
                    </li>
                  <% else %>
                    <li class="w-full lg:w-auto lg:mb-0 col-span-2 mb-2">
                      <%= link_to "Sign in", new_user_session_path, class: "btn btn-transparent lg:w-auto w-full", data: { turbo: false } %>
                    </li>
                    <li class="lg:pl-3 w-full lg:w-auto col-span-2">
                      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-dark lg:w-auto w-full", data: { turbo: false } %>
                    </li>
                  <% end %>
                </button>
              </li>
            </ul>
          </nav>
        </div>
      </div>