config/routes.rb
Rails.application.routes.draw do

	root action: :home, controller: "page"
	get 'privacy', to: 'page#privacy'
	get 'about', to: 'page#about'
	get 'home', to: 'page#home'
	get 'cookie', to: 'page#cookie'

	resources :dashboard, only: [:index] do
		collection do
			get :check
		end
	end

	resources :engines do
		resources :service_records do
			member do
				delete :remove_engine_service_record_image, to: 'service_records#remove_image', as: :remove_image
			end
		end
		member do
			delete :remove_image
		end
	end

	resources :events do
		collection do
			get :check
		end
	end

	namespace :api do
    namespace :v1 do
      resources :events, only: [:index, :show]
    end
  end

	resources :tracks do
		collection do
			get :search
		end
	end

	devise_for :users
	resources :contacts, only: [:new, :create]
	resources :championships
	resource :calendars, only: [:show]
	resources :follows, only: [:create, :destroy]

	get '*unmatched_route', to: 'application#not_found', constraints: lambda { |req|
		req.path.exclude? 'rails/active_storage'
	}

	if Rails.env.development? || Rails.env.test?
		mount Railsui::Engine, at: "/railsui"
	end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :championship, optional: true
  belongs_to :track

  has_and_belongs_to_many :categories

  has_many :follows, as: :followable, dependent: :destroy
  has_many :followers, through: :follows, source: :user
  has_one_attached :image

  validates :start_date, :end_date, :title, :description, :event_type, :track_id, presence: true
  validate :end_date_after_start_date

  scope :future_events, -> { where('start_date >= ?', Date.today).order(:start_date) }
  scope :past_events, -> { where('end_date < ?', Date.today).order(start_date: :desc) }
  scope :future_race_events, -> { future_events.where(event_type: 'Race') }
  scope :future_test_events, -> { future_events.where(event_type: 'Test') }
  scope :this_weekends_events, -> { future_events.where('end_date >= ? AND end_date <= ?', Date.today, Date.today + 7.days).includes(:track) }
  scope :next_week_events, -> { future_events.where('start_date >= ?', Date.today + 7.days) }
  scope :on_date, -> (date) { where('start_date <= ? AND end_date >= ?', date, date) }
  scope :by_category, ->(category_id) { joins(:categories).where(categories: { id: category_id }) }
  scope :by_event_type, ->(event_type) { where(event_type: event_type) }

  def self.followed_by(user)
    followed_event_ids = user.follows.where(followable_type: 'Event').pluck(:followable_id)
    where(id: followed_event_ids)
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApplicationController
  before_action :authenticate_with_api_key

  def index
    @events = Event.select(:id, :title, :start_date).all
    render json: @events.to_json(only: [:id, :title, :start_date])
  end

  def show
    @event = Event.find(params[:id])
    render json: @event.to_json(only: [:id, :title, :start_date, :end_date])
  end

  private

  def authenticate_with_api_key
    api_key = request.headers['X-Api-Key'] || params[:api_key]
    unless ApiKey.exists?(key: api_key)
      render json: { error: 'Unauthorized' }, status: :unauthorized
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: %i[index show test_events race_events check]
  before_action :ensure_admin_user!, except: %i[index show test_events race_events check create update new edit]

  def index
    selected_date = params[:date]
    event_type = params[:event_type]

    @next_week_events = Event.next_week_events.limit(6)
    @events = Event.on_date(selected_date)
    @this_weekends_events = Event.this_weekends_events
    @this_weekends_events = @this_weekends_events.by_event_type(event_type) if event_type.present?
    @no_events = @this_weekends_events.empty?
  end

  def show
    @event = Event.includes(:championship, :track).find(params[:id])
    
    @future_championship_events = Event.future_events
                   .where(championship: @event.championship)
                   .where.not(id: @event.id)
                   .order(start_date: :asc)

    @future_track_events = Event.future_events
                   .where(track: @event.track)
                   .where.not(id: @event.id)
                   .order(start_date: :asc)
  
    weather_service = WeatherService.new
    @weather_forecast = weather_service.parsed_weather_forecast(@event.track.longitude, @event.track.latitude)

    mapbox_service = MapboxService.new
    @hotels = mapbox_service.fetch_hotels(@event.track.longitude, @event.track.latitude)
    @fuel_stations = mapbox_service.fetch_fuel_stations(@event.track.longitude, @event.track.latitude)
  end

  def new
    @event = Event.new
    authorize @event, :new?
    @event.track = current_user.tracks.first if current_user.manager? && current_user.tracks.count == 1
  end

  def create
    @event = Event.new(event_params)
    @event.image = params[:event][:image]
    authorize @event, :create?
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @event, :edit?
  end

  def update
    authorize @event, :update?
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully deleted.'
  end

  def check
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])
    events = Event.where('start_date <= :end_date AND end_date >= :start_date', start_date: start_date, end_date: end_date).select(:start_date, :end_date)
    render json: (start_date..end_date).map { |date|
      {
        date: date,
        events: events.any? { |e| e.start_date <= date && e.end_date >= date }
      }
    }
  end

private

  def set_event
    @event = Event.includes(:categories).find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :price, :event_type, :image, :championship_id, :track_id, :start_date, :end_date, :licence, category_ids: [])
  end
  
end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/views/events/_event.html.erb
      <div class="mt-1 relative flex flex-row bg-white rounded-xl shadow-lg overflow-hidden transition-all duration-300 hover:shadow-xl">
        <div class="relative w-full md:w-2/5 h-auto">
          <%= image_tag random_default_image, alt: "Event Image", class: "object-cover w-full h-full" %>
          <div class="absolute top-0 left-0 m-4 flex-wrap xs:flex-col">
            <%= render 'shared/event_badges', event: event %>
          </div>
          <div class="absolute bottom-0 left-0 w-full h-1/3 bg-white bg-opacity-75 flex items-center justify-center">
            <div class="text-center text-gray-800">
              <div class="text-lg md:text-xl font-bold mb-1">
                <%= event.start_date.strftime("%B") %>
              </div>
              <div class="text-sm md:text-base">
                <% if event.start_date == event.end_date %>
                  <%= event.start_date.strftime("%A %-d") %><sup><%= event.start_date.day.ordinal %></sup>
                <% else %>
                  <%= event.start_date.strftime("%A %-d") %><sup><%= event.start_date.day.ordinal %></sup> - 
                  <%= event.end_date.strftime("%A %-d") %><sup><%= event.end_date.day.ordinal %></sup>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="p-4 flex flex-col justify-between w-full md:w-3/5">
          <div>
            <div class="flex items-center justify-between mb-1">
              <h5 class="text-xl font-bold text-gray-900 truncate">
                <% if event.championship&.logo.present? %>
                  <%= image_tag event.championship.logo, alt: "Championship Logo", class: "h-8 object-contain" %>
                <% elsif event.championship.present? %>
                  <%= event.championship.name %>
                <% elsif event.track&.logo.present? %>
                  <%= image_tag event.track.logo, alt: "Track Logo", class: "h-8 object-contain" %>
                <% else %>
                  <%= event.track.name %>
                <% end %>
              </h5>
            </div>
            <h4 class="text-lg font-semibold text-gray-900 mb-1"><%= event.title %></h4>
            <p class="text-sm text-gray-700 mb-4"><%= event.description.truncate(50, omission: '...') %></p>
          </div>
          <div class="flex items-start space-x-3">
            <dt class="">
              <span class="sr-only">Location</span>
              <!-- Heroicon name: mini/map-pin -->
              <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M9.69 18.933l.003.001C9.89 19.02 10 19 10 19s.11.02.308-.066l.002-.001.006-.003.018-.008a5.741 5.741 0 00.281-.14c.186-.096.446-.24.757-.433.62-.384 1.445-.966 2.274-1.765C15.302 14.988 17 12.493 17 9A7 7 0 103 9c0 3.492 1.698 5.988 3.355 7.584a13.731 13.731 0 002.273 1.765 11.842 11.842 0 00.976.544l.062.029.018.008.006.003zM10 11.25a2.25 2.25 0 100-4.5 2.25 2.25 0 000 4.5z" clip-rule="evenodd" />
              </svg>
            </dt>
            <dd class="text-sm text-gray-700 mb-4"><%= event.track.name %></dd>
          </div>
          <div class="flex flex-col md:flex-row md:space-y-0 space-y-2 items-center justify-center space-x-2 mt-2">
            <%= link_to event_path(event), class: "btn btn-primary", data: { turbo_frame: "_top" } do %>
              <span class="font-sans">View Event</span>
            <% end %>
            <% if current_user %>
              <%= render "shared/follow_button", followable: event %>
            <% else %>
              <%= link_to 'Add to My Calendar', new_user_session_path, class: "btn btn-primary btn-md", data: { turbo_frame: "_top" } %>
            <% end %>
          </div>
        </div>
      </div>

app/views/events/_form.html.erb
<div class="max-w-screen-lg mx-auto container px-5">
  <%= form_with(model: @event, local: true, html: { enctype: 'multipart/form-data' }) do |form| %>
    <% if @event.errors.any? %>
      <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative my-5" role="alert">
        <strong class="font-bold">Oops!</strong>
        <span class="block sm:inline"> <%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</span>

        <ul class="list-disc list-inside">
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    
    <div class="mb-4">
      <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :title, class: "form-input" %>
    </div>

    <div class="mb-4">
      <%= form.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_area :description, class: "form-input" %>
    </div>

    <div class="mb-4">
      <%= form.label :start_date, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.date_field :start_date, class: "form-input" %>
    </div>

    <div class="mb-4">
      <%= form.label :end_date, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.date_field :end_date, class: "form-input" %>
    </div>

    <div class="mb-4">
      <%= form.label :price, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.number_field :price, class: "form-input" %>
    </div>

    <div class="mb-4">
      <%= form.label :event_type, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.select :event_type, ['Race', 'Test'], {}, class: 'form-select' %>
    </div>

  
    <div class="mb-4">
      <%= form.label :licence, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.select :licence, ['NA', 'MSUK Licence', 'Non Licensed'], {}, class: 'form-select' %>
    </div>

    <% if current_user.manager? && current_user.tracks.count == 1 %>
    <div class="mb-4">
      <%= form.hidden_field :track_id, value: @event.track_id %>
      <p>Track: <%= @event.track.name %></p>
    </div>
    <% elsif current_user.admin? %>
    <div class="mb-4">
      <%= form.label :track, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.collection_select(:track_id, Track.all, :id, :name, {:prompt => 'Select a Track'}, { class: "mt-1 block w-full py-2 px-3 border rounded-md shadow-sm focus:ring focus:ring-opacity-50 text-white-800 bg-inherit" }) %>
    </div>
    <% else %>
    <div class="mb-4">
      <%= form.label :track, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.collection_select(:track_id, current_user.managed_tracks, :id, :name, {:prompt => 'Select a Track'}, { class: "mt-1 block w-full py-2 px-3 border rounded-md shadow-sm focus:ring focus:ring-opacity-50 text-white-800 bg-inherit" }) %>
    </div>
    <% end %>

    <% if current_user.manager? %>
      <% managed_track_ids = current_user.managed_tracks.pluck(:id) %>
      <% filtered_championships = Championship.where(user_id: current_user.id) %>
      <div class="mb-4">
        <%= form.label :championship, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.collection_select(:championship_id, filtered_championships, :id, :name, { include_blank: 'Select an option' }, { class: "mt-1 block w-full py-2 px-3 border rounded-md shadow-sm focus:ring focus:ring-opacity-50 text-black bg-white" }) %>
      </div>
    <% else %>
      <div class="mb-4">
        <%= form.label :championship, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.collection_select(:championship_id, Championship.all, :id, :name, { include_blank: 'Select an option' }, { class: "mt-1 block w-full py-2 px-3 border rounded-md shadow-sm focus:ring focus:ring-opacity-50 text-white-800 bg-inherit" }) %>
      </div>
    <% end %>

    <div class="mb-4">
      <%= form.label :image, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.file_field :image, class: "form-input" %>
    </div>

    <div class="mb-4">
      <%= form.label :categories, "Select Categories", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        <% Category.all.each do |category| %>
          <div>
            <%= check_box_tag "event[category_ids][]", category.id, @event.category_ids.include?(category.id), id: dom_id(category), class: "form-checkbox h-5 w-5 text-blue-600" %>
            <%= label_tag dom_id(category), category.name, class: "ml-2 text-sm font-medium text-white" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="flex items-center">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to 'Back', tracks_path, class: "btn btn-primary" %>
</div>

app/views/events/_weather.html.erb
<div class="w-full max-w-xl xl:px-8 xl:w-5/12">
  <div class="bg-white rounded shadow-2xl p-7 sm:p-10">
    <h2 class="text-2xl font-semibold text-center text-gray-800"><%= @event.track.location %></h2>
    <div class="max-w-md p-8 mx-auto rounded-lg dark:white dark:text-gray-800">
      <div class="flex justify-around space-x-4">
        <% if @event.start_date > Date.today + 7.days %>
          <p>Check back closer to the event date for weather updates</p>
        <% else %>
          <% if @weather_forecast.present? %>
            <% today_forecast = @weather_forecast[Date.today]&.first %>
            <% if today_forecast %>
              <div class="flex flex-col items-center">
                <%= image_tag "http://openweathermap.org/img/wn/#{today_forecast['weather'][0]['icon'].gsub('n', 'd')}.png", class: "w-16 h-16 fill-current" %>
                <h2 class="text-sm font-semibold text-center mt-5"><%= today_forecast['weather'][0]['description'].titleize %></h3>
              </div>
              <span class="inline-flex items-center">
              <span class="font-bold text-7xl leading-none"><%= today_forecast['main']['temp'].round %></span>
              <span class="font-bold text-3xl leading-none align-top">°C</span>
            </span>
            <% end %>
          <% end %>
        </div>
        <div class="flex justify-between mt-8 space-x-4 dark:text-gray-600">
        <% if @weather_forecast.present? %>
          <% @weather_forecast.keys.sort[1..5].each_with_index do |date, i| %>
            <div class="flex flex-col items-center space-y-1">
              <span class="uppercase"><%= date.strftime('%a') %></span>
            <% daily_forecast = @weather_forecast[date]&.first %>
            <% if daily_forecast %>
              <%= image_tag "http://openweathermap.org/img/wn/#{daily_forecast['weather'][0]['icon'].gsub('n', 'd')}.png", class: "w-8 h-8 fill-current" %>
              <span><%= daily_forecast['main']['temp'].round %>°C</span>
            <% else %>
              <span>No Data</span>
            <% end %>
          </div>
        <% end %>
      </div>
      <% end %>
        <% end  %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<% content_for :title, 'Edit Event' %>
<div class="container mx-auto px-4">
  <%= render partial: "events/form" %>
  <div class="mt-4">
  <h3>Admin Buttons</h3>
  <%= link_to 'Back', events_path, class: "btn btn-primary" %>
  <%= link_to 'Delete Event', event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn bg-red-700" %>
  </div>
</div>

app/views/events/index.html.erb
<div class="container mx-auto sm:py-24 pb-10 px-4 relative z-10 flex flex-wrap items-center justify-between mt-10">
  <div class="w-full text-center mb-10">
    <p class="text-indigo-600 font-medium mb-3 lg:mt-0 mt-2 dark:text-indigo-500">Next Up</p>
    <h1 class="sm:text-5xl text-4xl font-extrabold">This Week in Karting..</h1>
  </div>

  <div class="w-full flex flex-wrap justify-center mb-5">
    <%= link_to 'Test Events', events_path(event_type: 'Test', category_id: params[:category_id]), data: { turbo_frame: "filtered-events" }, class: "bg-green-200 text-green-900 px-3 py-1 m-0.5 rounded-full text-sm font-medium" %>
    <%= link_to 'Race Events', events_path(event_type: 'Race', category_id: params[:category_id]), data: { turbo_frame: "filtered-events" }, class: "bg-indigo-200 text-indigo-900 px-3 py-1 m-0.5 rounded-full text-sm font-medium" %>
    <%= link_to 'All Events', events_path(category_id: params[:category_id]), data: { turbo_frame: "filtered-events" }, class: "bg-gray-700 text-white px-3 py-1 m-0.5 rounded-full text-sm font-medium" %>
  </div>

  <turbo-frame id="filtered-events">
    <div class="w-full grid grid-cols-1 xl:grid-cols-2 gap-4 mt-5">
      <% if @no_events %>
        <p class="text-center text-gray-500">No events found for the selected criteria.</p>
      <% else %>
        <% @this_weekends_events.each do |event| %>
          <%= render "events/event", event: event %>
        <% end %>
      <% end %>
    </div>
  </turbo-frame>
</div>
    <div class="p-6 lg:col-span-12 md:col-span-12 col-span-12 rounded-lg shadow-sm border border-slate-200 bg-white dark:bg-slate-800 dark:border-none dark:text-slate-300">
      <div id="calendar-section" class="mb-6">        
          <%= turbo_frame_tag :calendar, src: calendars_path(date: Date.today) %>
    </div>
  </div>   

  <%= turbo_frame_tag :events do %>
    <%= render @events %>
  <% end %>

<div class="container mx-auto mt-8 px-4" id="future-events">
  <div class="w-full text-center mb-6">
    <p class="text-indigo-600 font-medium mb-3 lg:mt-0 mt-2 dark:text-indigo-500">Coming Soon</p>
    <h1 class="text-4xl font-extrabold">Future Events</h1>
  </div>
  <div class="grid grid-cols-1 md:grid-cols-2 gap-4 px-4">
    <% @next_week_events.each do |event| %>
      <%= render "events/event", event: event %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<% content_for :title, 'New Event' %>
  <div class="container mx-auto px-4">
    <%= render partial: "events/form" %>
  </div>